// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../atma-server
//   ../atma-server/HttpApplication/LifecycleEvents
//   ../@slack/web-api

declare module 'atma-server-monit' {
    import { LoggerFile } from 'atma-server-monit/fs/LoggerFile'; 
     import { Application } from 'atma-server';
    import { IMonitOptions } from 'atma-server-monit/MonitWorker';
    import { ILoggerOpts, EmptyLoggerFile } from 'atma-server-monit/fs/LoggerFile';
    export namespace Monit {
            function startLogger(opts: IMonitOptions): Promise<void>;
            function start(app: Application, opts: IMonitOptions): void;
            function createChannel(name: string, opts?: Partial<ILoggerOpts>): EmptyLoggerFile | LoggerFile;
            function flush(): void;
            function error(error: Error): void;
    }
}

declare module 'atma-server-monit/fs/LoggerFile' {
    import { ICsvColumn } from 'atma-server-monit/model/ICsvColumn';
    export interface ILoggerOpts {
        directory: string;
        fileCountMax?: number;
        fileBytesMax?: number;
        fileMessagesMax?: number;
        messageBufferMax?: number;
        writeTimeout?: number;
        fields?: ICsvColumn[];
        columns?: ICsvColumn[];
    }
    export interface ILogger {
        writeRow(cells: any[]): any;
        write(mix: string | any[]): void;
        flush(): any;
    }
    export class EmptyLoggerFile implements ILogger {
        writeRow(cells: any[]): void;
        write(mix: string | any[]): void;
        flush(): void;
    }
    export class LoggerFile implements ILogger {
        directory: string;
        opts: ILoggerOpts;
        static create(key: string, opts: ILoggerOpts): LoggerFile;
        static prepair(opts: ILoggerOpts): LoggerFile;
        static restore(directory: string, key: string, options?: ILoggerOpts): Promise<LoggerFile>;
        protected constructor();
        writeRow(cells: any[]): void;
        writeRows(cellsMany: any[][]): void;
        write(mix: string | any[]): void;
        flush(): void;
        protected init(opts: ILoggerOpts): void;
    }
}

declare module 'atma-server-monit/MonitWorker' {
    import { SlackClient } from 'atma-server-monit/Slack';
    import { LoggerFile, ILoggerOpts } from 'atma-server-monit/fs/LoggerFile';
    import { LifecycleEvent, LifecycleEvents } from 'atma-server/HttpApplication/LifecycleEvents';
    export interface IMonitOptions {
        directory?: string;
        channels?: {
            [name: string]: ILoggerOpts;
        };
        slack?: {
            token: string;
            channelId: string;
        };
        filterForSlack?: (event: LifecycleEvent) => boolean;
    }
    export class MonitWorker {
        events: LifecycleEvents;
        opts: IMonitOptions & {
            disableDefaultLoggers?: boolean;
        };
        slack: SlackClient;
        loggers: {
            start?: LoggerFile;
            requests?: LoggerFile;
            errors?: LoggerFile;
            [name: string]: LoggerFile;
        };
        constructor(events: LifecycleEvents, opts: IMonitOptions & {
            disableDefaultLoggers?: boolean;
        });
        createChannel(name: string, opts?: Partial<ILoggerOpts>): LoggerFile;
        watch(events: LifecycleEvents): void;
        writeError(error: Error): void;
        /** Flush all buffered content to disk */
        flush(): void;
        restoreChannelsAsync(): Promise<void>;
    }
}

declare module 'atma-server-monit/model/ICsvColumn' {
    export interface ICsvColumn {
        idx?: number;
        name: string;
        type: 'string' | 'number' | 'date' | 'text' | 'boolean';
        summable?: boolean;
        groupable?: boolean;
        sortable?: boolean;
        filterable?: boolean;
    }
}

declare module 'atma-server-monit/Slack' {
    import { WebClient } from '@slack/web-api';
    export class SlackClient {
        access_token: string;
        team_id: string;
        enterprise_id: string;
        web: WebClient;
        token: string;
        channelId: string;
        constructor(opts: {
            token: string;
            channelId: string;
        });
        login(): Promise<void>;
        send(message: string): Promise<void>;
    }
}

